export interface BuyOrder {
  _id: string;
  unitPrice: string;
  usdPrice: string;
  amountToPay: string;
  status: "paid" | "pending" | "failed" | string;
  bankName: string;
  accountName: string;
  accountNumber: string;
  selectedToken: {
    _id: string;
    chain: {
      _id: string;
      name: string;
      __v: number;
      createdAt: number;
      createdBy: string | null;
      explorerUrl: string;
      id: string;
      isActive: boolean;
      nativeToken: string;
      updatedAt: number;
      updatedBy: string | null;
    };
    chainCode:
      | "BTC"
      | "ETH"
      | "SOL"
      | "USDC-ERC20"
      | "USDT-ERC20"
      | "USDT-TRC20";
    rate: {
      _id: string;
      id: string;
      cryptoAsset: string;
      buyRate: number;
      sellRate: number;
    };
    symbol: string;
    __v: number;
    contractAddress: string;
    createdAt: number;
    createdBy: string | null;
    decimals: number;
    enableBuy: boolean;
    enableSell: boolean;
    id: string;
    isActive: boolean;
    logo: string;
    maximumTransaction: number;
    minimumTransaction: number;
    name: string;
    tokenType: "ERC20" | "TRC20" | string;
    updatedAt: number;
    updatedBy: string | null;
  };
  createdBy: {
    isPhoneVerified: boolean;
    _id: string;
    email: string;
    __v: number;
    avatar: string | null;
    bitcoinAddress: string;
    bitcoinMnemonic: string;
    country: string;
    createdAt: number;
    createdBy: string | null;
    ethereumAddress: string;
    ethereumMnemonic: string;
    firstname: string;
    id: string;
    isActive: boolean;
    isKYCDone: boolean;
    isVerified: boolean;
    lastname: string;
    password: string;
    phone: string;
    solanaAddress: string;
    solanaMnemonic: string;
    status: "Active" | "Inactive" | string;
    timezone: string;
    tronAddress: string;
    updatedAt: number;
    updatedBy: string | null;
    transactionPin: string;
    appleSub?: string;
    username: string;
    gender: "male" | "female" | string;
    devices: {
      deviceId: string;
      longitude: number;
      latitude: number;
      locationName: string;
      deviceName: string;
      _id: string;
    }[];
    is2faEnabled: boolean;
    secret2faCode: string;
  };
  updatedBy: {
    _id: string;
    email: string;
    __v: number;
    avatar: string | null;
    bitcoinAddress: string;
    bitcoinMnemonic: string;
    country: string;
    createdAt: number;
    createdBy: string | null;
    ethereumAddress: string;
    ethereumMnemonic: string;
    firstname: string;
    id: string;
    isActive: boolean;
    isKYCDone: boolean;
    isPhoneVerified: boolean;
    isVerified: boolean;
    lastname: string;
    password: string;
    phone: string;
    solanaAddress: string;
    solanaMnemonic: string;
    status: "Active" | "Inactive" | string;
    timezone: string;
    tronAddress: string;
    updatedAt: number;
    updatedBy: string | null;
    transactionPin: string;
    username: string;
    gender: "male" | "female" | string;
    devices: {
      deviceId: string;
      longitude: number;
      latitude: number;
      locationName: string;
      deviceName: string;
      _id: string;
    }[];
    is2faEnabled: boolean;
    secret2faCode: string;
    appleSub?: string;
  };
  createdAt: number;
  updatedAt: number;
  id: string;
  __v: number;
  transactionReceipt: string;
}

export interface SellOrder {
  _id: string;
  unitPrice: string;
  usdPrice: string;
  txnHash: string;
  chain: string;
  amountToPay: string;
  status: "pending" | "completed" | "failed" | "paid" | string;
  bankName: string;
  accountName: string;
  accountNumber: string;
  selectedToken: {
    _id: string;
    symbol: string;
    chain: {
      _id: string;
      name: string;
      __v: number;
      createdAt: number;
      createdBy: string | null;
      explorerUrl: string;
      id: string;
      isActive: boolean;
      nativeToken: string;
      updatedAt: number;
      updatedBy: string | null;
    };
    rate: {
      _id: string;
      id: string;
      cryptoAsset: string;
      buyRate: number;
      sellRate: number;
    };
    __v: number;
    contractAddress: string | null;
    createdAt: number;
    createdBy: string | null;
    decimals: number;
    enableBuy: boolean;
    enableSell: boolean;
    id: string;
    isActive: boolean;
    logo: string;
    maximumTransaction: number;
    minimumTransaction: number;
    name: string;
    tokenType: "Native" | "ERC20" | "BEP20" | string;
    updatedAt: number;
    updatedBy: string | null;
  };
  createdBy: {
    _id: string;
    email: string;
    __v: number;
    avatar: string | null;
    bitcoinAddress: string;
    bitcoinMnemonic: string;
    country: string;
    createdAt: number;
    createdBy: string | null;
    ethereumAddress: string;
    ethereumMnemonic: string;
    firstname: string;
    id: string;
    isActive: boolean;
    isKYCDone: boolean;
    isPhoneVerified: boolean;
    isVerified: boolean;
    lastname: string;
    password: string;
    phone: string;
    solanaAddress: string;
    solanaMnemonic: string;
    status: "Active" | "Inactive" | string;
    timezone: string;
    tronAddress: string;
    updatedAt: number;
    updatedBy: string | null;
    transactionPin: string;
    username: string;
    gender: "male" | "female" | string;
    devices: {
      deviceId: string;
      longitude: number;
      latitude: number;
      locationName: string;
      deviceName: string;
      _id: string;
    }[];
    is2faEnabled: boolean;
    secret2faCode: string;
    appleSub?: string;
  };
  updatedBy: {
    _id: string;
    email: string;
    __v: number;
    avatar: string | null;
    bitcoinAddress: string;
    bitcoinMnemonic: string;
    country: string;
    createdAt: number;
    createdBy: string | null;
    ethereumAddress: string;
    ethereumMnemonic: string;
    firstname: string;
    id: string;
    isActive: boolean;
    isKYCDone: boolean;
    isPhoneVerified: boolean;
    isVerified: boolean;
    lastname: string;
    password: string;
    phone: string;
    solanaAddress: string;
    solanaMnemonic: string;
    status: "Active" | "Inactive" | string;
    timezone: string;
    tronAddress: string;
    updatedAt: number;
    updatedBy: string | null;
    transactionPin: string;
    username: string;
    gender: "male" | "female" | string;
    devices: {
      deviceId: string;
      longitude: number;
      latitude: number;
      locationName: string;
      deviceName: string;
      _id: string;
    }[];
    is2faEnabled: boolean;
    secret2faCode: string;
    appleSub?: string;
  };
  createdAt: number;
  updatedAt: number;
  id: string;
  __v: number;
}

export interface Transaction {
  _id: string;
  id: string;
  user: UserInfo;
  chain: string;
  direction: "Sent" | "Received";
  status: "Pending" | "Success" | "Failed";
  amount: number;
  fee: number;
  from: string;
  to: string;
  hash: string;
  explorer: string;
  logo: string;
  timestamp: number;
  createdAt: number;
  updatedAt: number;
  __v: number;
}

export interface UserInfo {
  id: string;
  firstname: string;
  lastname: string;
  email: string;
  country: string;
  phone: string;
  avatar: string | null;
  ethereumAddress: string;
  solanaAddress: string;
  tronAddress: string;
  bitcoinAddress: string;
  isVerified: boolean;
  isActive: boolean;
  timezone: string;
}
